In [1]:
try:
    from variables import Variable
except:
    from AutoDiff.variables import Variable
try:
    from vectorize_func import vectorize_variable
except:
    from AutoDiff.vectorize_func import vectorize_variable
try:
    import AD_numpy as anp
except:
    import AutoDiff.AD_numpy as anp
    
try:
    import Optimizer as op
except:
    import AutoDiff.Optimizer as op
import numpy as np
from numpy.linalg import pinv
from numpy.linalg import norm

In [2]:
f = lambda x, y, z: (x-2)**5 + (y-3)**2 + (z-4)**2
#op.minimize(f, [3, 2, 1], method="Newton Method")
op.min_gradientdescent(f, [3, 2, 5], 1e-6, 50)

[2.85 2.04 4.9 ]
[2.77561411 2.079168   4.8118    ]
[2.72539004 2.11745929 4.73367562]
[2.6876602  2.15483417 4.66421597]
[2.65761051 2.19125801 4.60225503]
[2.63275994 2.22670126 4.54682041]
[2.61165728 2.26113937 4.49709452]
[2.5933797 2.2945527 4.4523849]
[2.57730411 2.32692642 4.41210107]
[2.56299033 2.35825028 4.37573644]
[2.55011612 2.38851841 4.34285397]
[2.53843869 2.41772911 4.31307467]
[2.52777072 2.44588457 4.28606838]
[2.51796479 2.47299062 4.26154621]
[2.50890286 2.49905641 4.23925438]
[2.50048903 2.52409413 4.21896918]
[2.49264439 2.54811876 4.2004927 ]
[2.48530323 2.5711477  4.18364933]
[2.47841033 2.59320055 4.16828285]
[2.47191883 2.6142988  4.15425384]
[2.46578864 2.63446556 4.14143764]
[2.45998526 2.65372532 4.12972254]
[2.45447873 2.67210368 4.11900818]
[2.44924292 2.68962714 4.10920426]
[2.44425492 2.70632288 4.10022941]
[2.43949449 2.72221859 4.09201014]
[2.43494374 2.73734222 4.08448001]
[2.4305867  2.75172191 4.07757887]
[2.42640913 2.76538575 4.07125219]
[2.422

In [3]:
def f(x):
    return (x[0]-2)**2 + (x[1]-3)**2 + (x[2]-4)**2
op.min_steepestdescent(f, [3, 2, 5], 1e-6, 50)


[2.94  2.142 4.9  ]
[2.995272   2.11208933 4.9882    ]
[2.93564979 2.24974101 4.88961322]
[2.9905846  2.23214133 4.97661051]
[2.93133605 2.3625136  4.8794063 ]
[2.98593723 2.36035281 4.96522592]
[2.9270583  2.48064489 4.86937462]
[2.98132937 2.4968972  4.95404084]
[2.92281605 2.60510284 4.85951369]
[2.97676048 2.64231349 4.94305006]
[2.91860884 2.73853412 4.84981919]
[2.97223004 2.79891812 4.93224858]
[2.91443621 2.88902826 4.84028694]
[2.96773753 2.97958274 4.92163154]
[2.91029771 2.96239976 4.83091292]
[2.96328246 2.99386131 4.91119428]
[2.9061929  2.98867028 4.82169324]
[2.95886433 2.99823435 4.9009323 ]
[2.90212134 2.9967391  4.81262413]
[2.95448265 2.99949925 4.89084122]
[2.8980826  2.999075   4.80370196]
[2.95013695 2.99985856 4.88091686]
[2.89407627 2.99973872 4.79492322]
[2.94582677 2.9999601  4.87115513]
[2.89010193 2.99992629 4.7862845 ]
[2.94155164 2.99998875 4.86155212]
[2.88615918 2.99997921 4.77778251]
[2.93731111 2.99999683 4.85210403]
[2.88224763 2.99999414 4.76941408]


In [4]:
from scipy.optimize import fmin
fmin(f, [3,2,3])

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 68
         Function evaluations: 124


array([2.00002227, 3.00002265, 3.99997193])

In [6]:
def min_gradientdescent(fn, x0, precision, max_iter, lr=0.01):
     # create initial variables
    # right now we only test with the 26 alphabets
    from string import ascii_lowercase
    import time
    import numpy as np

    name_ls = iter(ascii_lowercase)

    # create initial variables
    var_names = []
    for i in x0:
        name = next(name_ls)
        var_names.append(name)

    x = np.array(x0)
    s = 0 # initialize as 0 works to ensure that s=g in 1st iteration

    nums_iteration = 0
    val_rec = []
    time_rec = []
    init_time = time.time()
     # initial guess of n = 0.01
    n = 0.01
    while True:
        # recreate new variables with new values
        x_var = []
        for i, v in enumerate(x):
            x_var.append(Variable(var_names[i], v))
        # obtain values and jacobian to find delta_f
        val_vector = np.array([value.val for value in x_var])
        jacobian = np.array([fn(*x_var).der.get(i) for i in var_names])
        delta_f = jacobian*val_vector


        # update x
        old_x = x
        x = x - lr*delta_f
        print(x)
        # threshold stopping condition
        if max(abs(x-old_x)) < precision:
            return Result(x, val_rec, time_rec, True)

        # store history of values
        val_rec.append(x)

        time_rec.append(time.time()-init_time)

        # iteration stopping condition
        if nums_iteration >= max_iter:
            return Result(x, val_rec    , time_rec, False)
        nums_iteration +=1


In [5]:
def min_steepestdescent(fn, x0, precision, max_iter):
     # create initial variables
    # right now we only test with the 26 alphabets
    from string import ascii_lowercase
    import time
    import numpy as np
    from scipy.optimize import fmin

    name_ls = iter(ascii_lowercase)

    # create initial variables
    var_names = []
    for i in x0:
        name = next(name_ls)
        var_names.append(name)

    x = np.array(x0)
    s = 0 # initialize as 0 works to ensure that s=g in 1st iteration

    nums_iteration = 0
    val_rec = []
    time_rec = []
    init_time = time.time()
     # initial guess of n = 0.01
    n = 0.01
    while True:
        # recreate new variables with new values
        x_var = []
        for i, v in enumerate(x):
            x_var.append(Variable(var_names[i], v))
        # obtain values and jacobian to find delta_f
        val_vector = np.array([value.val for value in x_var])
        jacobian = np.array([fn(x_var).der.get(i) for i in var_names])
        delta_f = jacobian*val_vector


        find_min = fmin(fn, val_vector-n*delta_f, maxiter = 1, disp=False)
        n = (find_min - x)/delta_f

        # update x
        old_x = x
        x = x + n*delta_f

        # threshold stopping condition
        if max(abs(x-old_x)) < precision:
            return Result(x, val_rec, time_rec, True)

        # store history of values
        val_rec.append(x)

        time_rec.append(time.time()-init_time)

        # iteration stopping condition
        if nums_iteration >= max_iter:
            return Result(x, val_rec    , time_rec, False)
        nums_iteration +=1
