In [1]:
try:
    from variables import Variable
except:
    from AutoDiff.variables import Variable
try:
    from vectorize_func import vectorize_variable
except:
    from AutoDiff.vectorize_func import vectorize_variable
try:
    import AD_numpy as anp
except:
    import AutoDiff.AD_numpy as anp
    
try:
    import Optimizer as op
except:
    import AutoDiff.Optimizer as op
import numpy as np
from numpy.linalg import pinv
from numpy.linalg import norm

In [4]:
f = lambda x, y, z: (x-2)**5 + (y-3)**2 + (z-4)**2
#op.minimize(f, [3, 2, 1], method="Newton Method")
op.min_gradientdescent(f, [3, 2, 5], 1e-6, 50)

[2.85 2.04 4.9 ]
[2.77561411 2.079168   4.8118    ]
[2.72539004 2.11745929 4.73367562]
[2.6876602  2.15483417 4.66421597]
[2.65761051 2.19125801 4.60225503]
[2.63275994 2.22670126 4.54682041]
[2.61165728 2.26113937 4.49709452]
[2.5933797 2.2945527 4.4523849]
[2.57730411 2.32692642 4.41210107]
[2.56299033 2.35825028 4.37573644]
[2.55011612 2.38851841 4.34285397]
[2.53843869 2.41772911 4.31307467]
[2.52777072 2.44588457 4.28606838]
[2.51796479 2.47299062 4.26154621]
[2.50890286 2.49905641 4.23925438]
[2.50048903 2.52409413 4.21896918]
[2.49264439 2.54811876 4.2004927 ]
[2.48530323 2.5711477  4.18364933]
[2.47841033 2.59320055 4.16828285]
[2.47191883 2.6142988  4.15425384]
[2.46578864 2.63446556 4.14143764]
[2.45998526 2.65372532 4.12972254]
[2.45447873 2.67210368 4.11900818]
[2.44924292 2.68962714 4.10920426]
[2.44425492 2.70632288 4.10022941]
[2.43949449 2.72221859 4.09201014]
[2.43494374 2.73734222 4.08448001]
[2.4305867  2.75172191 4.07757887]
[2.42640913 2.76538575 4.07125219]
[2.422

[2.21306174 2.99999998 4.        ]
[2.21283372 2.99999998 4.        ]
[2.21260669 2.99999998 4.        ]
[2.21238065 2.99999998 4.        ]
[2.21215559 2.99999998 4.        ]
[2.21193151 2.99999998 4.        ]
[2.2117084  2.99999999 4.        ]
[2.21148625 2.99999999 4.        ]
[2.21126505 2.99999999 4.        ]
[2.2110448  2.99999999 4.        ]
[2.21082548 2.99999999 4.        ]
[2.2106071  2.99999999 4.        ]
[2.21038964 2.99999999 4.        ]
[2.2101731  2.99999999 4.        ]
[2.20995748 2.99999999 4.        ]
[2.20974275 2.99999999 4.        ]
[2.20952893 2.99999999 4.        ]
[2.20931599 2.99999999 4.        ]
[2.20910394 2.99999999 4.        ]
[2.20889277 2.99999999 4.        ]
[2.20868247 2.99999999 4.        ]
[2.20847304 2.99999999 4.        ]
[2.20826446 2.99999999 4.        ]
[2.20805674 3.         4.        ]
[2.20784987 3.         4.        ]
[2.20764383 3.         4.        ]
[2.20743864 3.         4.        ]
[2.20723427 3.         4.        ]
[2.20703072 3.      

[2.17220288 3.         4.        ]
[2.17210737 3.         4.        ]
[2.17201208 3.         4.        ]
[2.171917 3.       4.      ]
[2.17182214 3.         4.        ]
[2.1717275 3.        4.       ]
[2.17163306 3.         4.        ]
[2.17153884 3.         4.        ]
[2.17144482 3.         4.        ]
[2.17135102 3.         4.        ]
[2.17125743 3.         4.        ]
[2.17116404 3.         4.        ]
[2.17107086 3.         4.        ]
[2.17097789 3.         4.        ]
[2.17088513 3.         4.        ]
[2.17079257 3.         4.        ]
[2.17070021 3.         4.        ]
[2.17060806 3.         4.        ]
[2.17051611 3.         4.        ]
[2.17042436 3.         4.        ]
[2.17033282 3.         4.        ]
[2.17024147 3.         4.        ]
[2.17015032 3.         4.        ]
[2.17005938 3.         4.        ]
[2.16996863 3.         4.        ]
[2.16987807 3.         4.        ]
[2.16978772 3.         4.        ]
[2.16969756 3.         4.        ]
[2.16960759 3.         4.    

[2.15171617 3.         4.        ]
[2.15165917 3.         4.        ]
[2.15160226 3.         4.        ]
[2.15154543 3.         4.        ]
[2.15148869 3.         4.        ]
[2.15143204 3.         4.        ]
[2.15137547 3.         4.        ]
[2.15131899 3.         4.        ]
[2.15126259 3.         4.        ]
[2.15120628 3.         4.        ]
[2.15115005 3.         4.        ]
[2.15109391 3.         4.        ]
[2.15103786 3.         4.        ]
[2.15098189 3.         4.        ]
[2.150926 3.       4.      ]
[2.1508702 3.        4.       ]
[2.15081448 3.         4.        ]
[2.15075885 3.         4.        ]
[2.1507033 3.        4.       ]
[2.15064783 3.         4.        ]
[2.15059244 3.         4.        ]
[2.15053714 3.         4.        ]
[2.15048192 3.         4.        ]
[2.15042678 3.         4.        ]
[2.15037173 3.         4.        ]
[2.15031676 3.         4.        ]
[2.15026187 3.         4.        ]
[2.15020706 3.         4.        ]
[2.15015233 3.         4.       

In [1]:
op.min_steepestdescent(f, [3, 2, 5], 1e-6, 50)

NameError: name 'op' is not defined

In [7]:
def f(x):
    return (x[0]-2)**2 + (x[1]-3)**2 + (x[2]-4)**2
op.min_steepestdescent(f, [3, 2, 5], 1e-6, 50)


In [4]:
from scipy.optimize import fmin
fmin(f, [3,2,3])

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 68
         Function evaluations: 124


array([2.00002227, 3.00002265, 3.99997193])

In [6]:
def min_gradientdescent(fn, x0, precision, max_iter, lr=0.01):
     # create initial variables
    # right now we only test with the 26 alphabets
    from string import ascii_lowercase
    import time
    import numpy as np

    name_ls = iter(ascii_lowercase)

    # create initial variables
    var_names = []
    for i in x0:
        name = next(name_ls)
        var_names.append(name)

    x = np.array(x0)
    s = 0 # initialize as 0 works to ensure that s=g in 1st iteration

    nums_iteration = 0
    val_rec = []
    time_rec = []
    init_time = time.time()
     # initial guess of n = 0.01
    n = 0.01
    while True:
        # recreate new variables with new values
        x_var = []
        for i, v in enumerate(x):
            x_var.append(Variable(var_names[i], v))
        # obtain values and jacobian to find delta_f
        val_vector = np.array([value.val for value in x_var])
        jacobian = np.array([fn(*x_var).der.get(i) for i in var_names])
        delta_f = jacobian*val_vector


        # update x
        old_x = x
        x = x - lr*delta_f
        print(x)
        # threshold stopping condition
        if max(abs(x-old_x)) < precision:
            return Result(x, val_rec, time_rec, True)

        # store history of values
        val_rec.append(x)

        time_rec.append(time.time()-init_time)

        # iteration stopping condition
        if nums_iteration >= max_iter:
            return Result(x, val_rec    , time_rec, False)
        nums_iteration +=1


In [5]:
def min_steepestdescent(fn, x0, precision, max_iter):
     # create initial variables
    # right now we only test with the 26 alphabets
    from string import ascii_lowercase
    import time
    import numpy as np
    from scipy.optimize import fmin

    name_ls = iter(ascii_lowercase)

    # create initial variables
    var_names = []
    for i in x0:
        name = next(name_ls)
        var_names.append(name)

    x = np.array(x0)
    s = 0 # initialize as 0 works to ensure that s=g in 1st iteration

    nums_iteration = 0
    val_rec = []
    time_rec = []
    init_time = time.time()
     # initial guess of n = 0.01
    n = 0.01
    while True:
        # recreate new variables with new values
        x_var = []
        for i, v in enumerate(x):
            x_var.append(Variable(var_names[i], v))
        # obtain values and jacobian to find delta_f
        val_vector = np.array([value.val for value in x_var])
        jacobian = np.array([fn(x_var).der.get(i) for i in var_names])
        delta_f = jacobian*val_vector


        find_min = fmin(fn, val_vector-n*delta_f, maxiter = 1, disp=False)
        n = (find_min - x)/delta_f

        # update x
        old_x = x
        x = x + n*delta_f

        # threshold stopping condition
        if max(abs(x-old_x)) < precision:
            return Result(x, val_rec, time_rec, True)

        # store history of values
        val_rec.append(x)

        time_rec.append(time.time()-init_time)

        # iteration stopping condition
        if nums_iteration >= max_iter:
            return Result(x, val_rec    , time_rec, False)
        nums_iteration +=1
